
ALTER TABLE users
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE users
    ADD COLUMN updated_at TIMESTAMPTZ NULL;

ALTER TABLE users
    ADD COLUMN status VARCHAR(20) DEFAULT 'ACTIVE';